### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by LuanRoger** [vinioliveira7/Book-Management#7]
# Lista de afazeres
Maioria dos problemas são de estética e organização, portanto, não são prioridades.

- [x] Exibir mensagem de sucesso quando cadastrar uma nova encomenda. - 332d695130a33fe5cc976815ba889b20b54c8d6e
- [x] Exibir mensagem de sucesso quando cadastrar um novo pedido. - 332d695130a33fe5cc976815ba889b20b54c8d6e
- [x] Criar separadores entre uma encomenda/pedido e outra ao exibir. - ???
- [x] Organizar o arquivo a arvore binaria. - af9bcb548d52aa7a03b45b3b5fdbe25925000b52
- [x] Renomear arquivos para o português. - 4b03e32f7b7270bbcde880c384edd2d344636ee1
- [x] Rever algoritmo de geração de IDs para a arvore binaria. - ebbf120dac00288ee44d04c4bda7445cbba681c7
- [x] Consertar o adicionar na fila de prioridade. - #9

**Comment by LuanRoger** [comment]
Sugestão: Trocar os IFs do menu da main por switch/case

Evita de ter muita camada de if dentro do outro, além de ficar mais legível sobre o contexto do menu e lógica das funcionalidades.
